let btn_nav=document.getElementById("btn");let nav_bar=document.querySelector("nav");let arrow_a=document.querySelector(".arrow-a");btn_nav.addEventListener("click",open_nav);document.addEventListener("keydown",function(e){if(e.code=="ArrowRight"){open_nav();if(nav_bar.classList.contains("active")){window.addEventListener("keydown",function(e){if(e.code=="Enter"){}})}}});document.addEventListener("keydown",function(e){if(e.keyCode>=65&&e.keyCode<=90||e.keyCode==18){if(nav_bar.classList.contains("cancello")){control_menu()
nav_bar.classList.remove("cancello");nav_bar.classList.add("active")}}});function open_nav(){if(nav_bar.classList.contains("cancello")){nav_bar.classList.remove("cancello");nav_bar.classList.add("active")}else{nav_bar.classList.remove("active");nav_bar.classList.add("cancello")}
control_menu()}
function control_menu(){let bbttn=document.querySelector('.button');bbttn.querySelector('span').classList.toggle('is-closed')}
let arrow=document.querySelector(".li-sub-main");let sub=document.querySelector(".sub");arrow.addEventListener("click",function(){if(sub.classList.contains("cancello")){sub.classList.remove("cancello");sub.classList.add("active");arrow_a.innerHTML=`<svg xmlns="http://www.w3.org/2000/svg" class="ionicon" width='25px' viewBox="0 0 512 512"><path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="48" d="M112 328l144-144 144 144"/></svg>`}else{sub.classList.remove("active");sub.classList.add("cancello");arrow_a.innerHTML=`<svg xmlns="http://www.w3.org/2000/svg" class="ionicon" width='25px' viewBox="0 0 512 512"><path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="48" d="M112 184l144 144 144-144"/></svg>`}});let a_mode=document.querySelector(".mode");let switch_btn=document.getElementById("switch-round");if(localStorage.getItem("check")=="true"){switch_btn.setAttribute("checked","true")}
a_mode.addEventListener("click",function(){if(switch_btn.getAttribute("checked")==null){switch_btn.setAttribute("checked","true");localStorage.setItem("check","true")}else{switch_btn.removeAttribute("checked");localStorage.removeItem("check")}});let dark_animation=document.querySelector("#dark_animation");let icon_mode=document.getElementById("icon_mode");let text_mode=document.getElementById("text_mode");if(localStorage.getItem("check")){icon_mode.innerHTML=`<svg xmlns="http://www.w3.org/2000/svg" class="ionicon" width='27px' viewBox="0 0 512 512"><path fill="none" stroke="currentColor" stroke-linecap="round" stroke-miterlimit="10" stroke-width="32" d="M256 48v48M256 416v48M403.08 108.92l-33.94 33.94M142.86 369.14l-33.94 33.94M464 256h-48M96 256H48M403.08 403.08l-33.94-33.94M142.86 142.86l-33.94-33.94"/><circle cx="256" cy="256" r="80" fill="none" stroke="currentColor" stroke-linecap="round" stroke-miterlimit="10" stroke-width="32"/></svg>`;text_mode.innerHTML=`light mode`;if(localStorage.getItem("check-dark-op")){dark_open()}
if(localStorage.getItem("check-dark-op")===null){dark_close()}
dark_mode()}
a_mode.addEventListener("click",function(){if(switch_btn.getAttribute("checked")=="true"){icon_mode.innerHTML=`<svg xmlns="http://www.w3.org/2000/svg" class="ionicon" width='27px' viewBox="0 0 512 512"><path fill="none" stroke="currentColor" stroke-linecap="round" stroke-miterlimit="10" stroke-width="32" d="M256 48v48M256 416v48M403.08 108.92l-33.94 33.94M142.86 369.14l-33.94 33.94M464 256h-48M96 256H48M403.08 403.08l-33.94-33.94M142.86 142.86l-33.94-33.94"/><circle cx="256" cy="256" r="80" fill="none" stroke="currentColor" stroke-linecap="round" stroke-miterlimit="10" stroke-width="32"/></svg>`;text_mode.innerHTML=`light mode`;if(localStorage.getItem("check-dark-op")){dark_open()}
if(localStorage.getItem("check-dark-op")===null){dark_close()}
dark_mode()}else{icon_mode.innerHTML=`<svg xmlns="http://www.w3.org/2000/svg" class="ionicon" width='27px' viewBox="0 0 512 512"><path d="M160 136c0-30.62 4.51-61.61 16-88C99.57 81.27 48 159.32 48 248c0 119.29 96.71 216 216 216 88.68 0 166.73-51.57 200-128-26.39 11.49-57.38 16-88 16-119.29 0-216-96.71-216-216z" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="32"/></svg>`;text_mode.innerHTML=`dark mode`;light_mode()}});if(localStorage.getItem("check-dark-op")=="true"){dark_animation.setAttribute("checked","true");dark_open();work()}
dark_animation.addEventListener("click",function(){if(dark_animation.getAttribute("checked")==null){dark_animation.setAttribute("checked","true");localStorage.setItem("check-dark-op","true");dark_open();work()}else{dark_animation.removeAttribute("checked");localStorage.removeItem("check-dark-op");dark_close();off()}});function dark_open(){dark_animation.setAttribute("checked","true");let app=document.querySelector("#particles-js");app.style.width="100%"}
function work(){const script_=document.createElement("script");script_.src="particles.js";script_.defer='true';script_.onload=()=>{const script__=document.createElement("script");script__.defer='true';script__.src="app.js";script__.onload=()=>{console.log("Script loaded successfully")};document.body.appendChild(script__)};document.body.appendChild(script_)}
function dark_close(){dark_animation.removeAttribute("checked");let app=document.querySelector("#particles-js");app.style.width="0%"}
function off(){let v=document.querySelectorAll("script");for(let i=0;i<v.length;i++){if(v[i].src.includes("app",0)){v[i].remove()}
if(v[i].src.includes("particles",0)){v[i].remove()}}}
if(localStorage.getItem("check-dark-op")){dark_open()}
if(localStorage.getItem("check-dark-op")===null){dark_close()}
let search=document.getElementById("search");let boxResult=document.querySelector(".box-result");let item=document.querySelectorAll(".info");let box_search_result=document.querySelector(".box-search-result");for(let i=0;i<item.length;i++){item[i].setAttribute("data_id",Date.now()+i);item[i].parentElement.setAttribute("id",Date.now()+i)}
let array=[];search.addEventListener("input",check);function check(){ch();for(let i=0;i<item.length;i++){let match=item[i].innerHTML.toLocaleLowerCase();let element_colne=item[i].cloneNode();element_colne.classList.add("clone");if(match.indexOf(search.value.toLocaleLowerCase())>-1&&search.value.length!==0&&search.value!==" "){element_colne.innerHTML=`<a href='#${item[i].parentElement.getAttribute(
        "id"
      )}'<span class='vv'><svg xmlns="http://www.w3.org/2000/svg" class="ionicon" width='20px' viewBox="0 0 512 512"><path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="32" d="M464 128L240 384l-96-96M144 384l-96-96M368 128L232 284"/></svg></span>${item[
        i
      ].innerHTML.toLocaleLowerCase()}</a><br>`;boxResult.appendChild(element_colne);array.push(element_colne);element_colne.addEventListener("click",a);function a(){item.forEach((e)=>{e.parentElement.style.backgroundColor="#ffffff80"});item[i].parentElement.style.backgroundColor="#a1c1f4";item[i].parentElement.onclick=function(){item[i].parentElement.style.backgroundColor="#ffffff80"}}}}}
function ch(){let elemnts=document.querySelectorAll(".clone");for(let i=0;i<array.length;i++){elemnts.forEach((e)=>{if(e.getAttribute("data_id")===array[i].getAttribute("data_id")){e.remove()}})}}
if(localStorage.getItem("check")!=="true"){let app=document.querySelector("#particles-js");app.style.width="0%"}
if(localStorage.getItem("check")==="true"&&localStorage.getItem("check-dark-op")=="true"){let app=document.querySelector("#particles-js");app.style.width="100%"}
function dark_mode(){document.body.classList.remove('light-mode');document.body.classList.add('dark-mode');let m=document.querySelector('.mode')
m.style.color="#fff";let box_text=document.querySelector(".pl");let x_sign=document.querySelectorAll("x-sign");box_text.style.display="none";x_sign.forEach((e)=>{e.style.cssText=`  color: yellow; --color1: goldenrod; --color2: orangered; --color3: mediumblue; --color4: purple; font-family: Gruppo; --interval: 1s; display: block; text-shadow:    0 0 10px var(--color1),   0 0 20px var(--color2),   0 0 40px var(--color3),   0 0 80px var(--color4); will-change: filter, color; filter: saturate(60%);  text-transform: uppercase; white-space: nowrap; font-weight: 400; animation: flicker steps(100) var(--interval) 1s infinite;`})}
function light_mode(){document.body.classList.remove('dark-mode');document.body.classList.add('light-mode');let box_text=document.querySelector(".pl");let x_sign=document.querySelectorAll("x-sign");x_sign.forEach((e)=>{e.removeAttribute('style')})
let m=document.querySelector('.mode')
m.style.color="#000";let app=document.querySelector("#particles-js");app.style.width="0%";box_text.style.display="block"}
setTimeout((_)=>{ityped.init(document.querySelector("#ityed-mes"),{strings:[`version 1.0.0 made with love by A|B|D|O`],loop:!1,})},2000);let to=document.querySelector(".to-top");document.body.onscroll=function(){if(scrollY>=1000){to.style.display="block"}else{to.style.display="none"}};to.onclick=function(){window.scrollTo(0,0)};let back_bth=document.querySelector("#back");back_bth.addEventListener("click",function(){if(back_bth.getAttribute("checked")===null){window.localStorage.setItem("dis-change-d-l","true");dis_background()}else{document.body.removeAttribute('style')
window.localStorage.setItem('back','open')
en_background()}});if(window.localStorage.getItem("dis-change-d-l")){dis_background()}else{en_background()}
function dis_background(){let mode_a_a=document.querySelector(".mode");let box=document.createElement("div");box.classList="c-block";mode_a_a.style.cssText="z-index:-1; color:#7c7c7c ; opacity:0.4;";box.style.cssText="height:70px;width:250px;position:absolute;right: 0px;z-index: 99999;";mode_a_a.append(box);document.querySelector("#switch-round").setAttribute("disabled","true");change_color()}
function en_background(){if(localStorage.check=="true"){let mode_a_a=document.querySelector(".mode");mode_a_a.style.cssText="z-index:20;"}else{let mode_a_a=document.querySelector(".mode");mode_a_a.style.cssText="z-index:20;"}
document.querySelector("#switch-round").removeAttribute("disabled");window.localStorage.removeItem("dis-change-d-l")}
function change_color(){light_mode();document.body.style.cssText=` --bgColor :${window.localStorage.getItem("color") ?? '#f6f5ff '};--bg:${window.localStorage.getItem("color") ?? '#f6f5ff '};  --bg-nav:${window.localStorage.getItem("color") ?? '#f6f5ff '};--cv:${window.localStorage.getItem("color_text") ?? '#000 '};`
let colors=document.querySelectorAll("#color");let nav=document.querySelector('nav');colors.forEach((e)=>{e.onclick=function(){colors.forEach((e)=>{e.classList.remove("cl")});e.classList.add("cl");nav.style.backgroundColor=`${e.getAttribute("data-color")}`;document.body.style.backgroundColor=`${e.getAttribute("data-color")}`;window.localStorage.setItem("color",`${e.getAttribute("data-color")}`)}});color_c()}
let colors=document.querySelectorAll("#color");let sec_color=document.querySelector("#sect_color");if(window.localStorage.getItem("c_c")){sec_color.value=`${window.localStorage.getItem("c_c")}`;colors[3].setAttribute("data-color",window.localStorage.getItem("c_c"));colors[3].setAttribute("style",`--cl:${window.localStorage.getItem("c_c")}`)}
sec_color.oninput=function(){let colors=document.querySelectorAll("#color");colors[3].setAttribute("data-color",sec_color.value);colors[3].setAttribute("style",`--cl:${sec_color.value}`);window.localStorage.setItem("c_c",sec_color.value);colors[3].click()};function change_color_color(){let c_c=document.querySelector("#c_c");let box_c_v=document.querySelector(".box-c-v");let block_cv=document.querySelector(".block-cv ");let close_c=document.querySelector("#close_c");c_c.addEventListener("click",function(){change_color();dis_background();if(document.querySelector('#back').getAttribute('checked')!='true'){document.querySelector('#back').click()}
c_c.setAttribute("checked","true");if(c_c.getAttribute("checked")=="true"){box_c_v.style.display="flex";block_cv.style.display="block"}else{box_c_v.style.display="none";block_cv.style.display="none"}});close_c.onclick=(_)=>c();block_cv.onclick=(_)=>c();function c(){box_c_v.style.display="none";block_cv.style.display="none";c_c.removeAttribute("checked")}}
change_color_color();function color_c(){let e_21=document.querySelectorAll("#e_21");let app=document.querySelector("#particles-js");app.style.width="0%";ccc();function ccc(){window.localStorage.setItem('dis-change-d-l','true');document.body.style.cssText=`--bgColor :${window.localStorage.getItem("color") ?? '#f6f5ff '}; --bg:${window.localStorage.getItem("color") ?? '#f6f5ff '};  --bg-nav:${window.localStorage.getItem("color") ?? '#f6f5ff '}; --color:${localStorage.getItem("color_text") ?? '#000'};--color-nav:${localStorage.getItem("color_text") ?? '#000'}; --color-title:${localStorage.getItem("color_text") ?? '#000'}; --cv:${window.localStorage.getItem("color_text") ?? '#000 '};`}
e_21.forEach((e)=>{e.addEventListener("click",function(){window.localStorage.setItem("color_text",e.getAttribute("data-color"));ccc()})})}
let color_v_select=document.querySelector("#color_v");let e_21=document.querySelectorAll("#e_21");e_21[2].setAttribute("data-color",window.localStorage.getItem("text_aaa"));e_21[2].setAttribute("style",`--cll:${window.localStorage.getItem("text_aaa")}`);color_v_select.value=window.localStorage.getItem("text_aaa");color_v_select.oninput=function(){e_21[2].setAttribute("data-color",color_v_select.value);e_21[2].setAttribute("style",`--cll:${color_v_select.value}`);window.localStorage.setItem("text_aaa",color_v_select.value);e_21[2].click()};window.onload=function(){const script_data=document.createElement("script");script_data.src="https://aomarah8.github.io/hu-lectures/data.js";script_data.async='true'
document.body.appendChild(script_data)}
